services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./symfony:/app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./symfony:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/symfony"
      MAILER_DSN: smtp://mailpit:1025

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  gotenberg:
    image: thecodingmachine/gotenberg:7
    container_name: gotenberg
    ports:
      - "3000:3000"
    environment:
      - DISABLE_GOOGLE_CHROME=false

volumes:
  db_data:
