security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            switch_user: true
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_dashboard
            logout:
                path: app_logout
                target: /

    access_control:
        - { path: ^/backoffice/school, roles: ['ROLE_ADMIN','ROLE_SUPER_ADMIN']  }
        - { path: ^/backoffice/assignment, roles: ['ROLE_ADMIN','ROLE_SUPER_ADMIN']  }
        - { path: ^/backoffice/assessment, roles: ['ROLE_ADMIN','ROLE_SUPER_ADMIN']  }
        - { path: ^/backoffice/user, roles: ['ROLE_ADMIN','ROLE_SUPER_ADMIN']  }
        - { path: ^/backoffice/category, roles: ['ROLE_ADMIN','ROLE_SUPER_ADMIN']  }
        - { path: ^/backoffice/diploma/assign, roles: IS_AUTHENTICATED_FULLY  }
        - { path: ^/backoffice/diploma, roles: ['ROLE_ADMIN','ROLE_SUPER_ADMIN']  }
        - { path: ^/backoffice, roles: IS_AUTHENTICATED_FULLY  }
        - { path: ^/subscription, roles: ['ROLE_ADMIN','ROLE_SUPER_ADMIN'] }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS }